before_script:
  - rustc --version
  - rustdoc --version
  - cargo --version

test:
  script:
    - cargo test
    - cargo build
    - tests/run_all.sh

release:
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/bender

doc:
  script:
    - cargo doc
  allow_failure: true
  artifacts:
    paths:
      - target/doc
