before_script:
  - rustc --version
  - rustdoc --version
  - cargo --version

test:
  script:
    - cargo test

release:
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/landa

doc:
  script:
    - cargo doc
  allow_failure: true
  artifacts:
    paths:
      - target/doc
