[package]
name = "landa"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
clap = "2.20.0"
semver = "0.5.1"
futures = "0.1"
futures-cpupool = "0.1"
tokio-process = "0.1.5"
blake2 = "0.7.0"
