[package]
name = "landa"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
yaml-rust = "0.3.5"
clap = "2.20.0"
semver = "0.5.1"
